"""Add email verification model

Revision ID: 19dc9714d9ea
Revises: 11781e907181
Create Date: 2026-03-19 12:22:16.244801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "19dc9714d9ea"
down_revision: Union[str, Sequence[str], None] = "11781e907181"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_tokens_id"), "verification_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_tokens_token"),
        "verification_tokens",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_tokens_token"), table_name="verification_tokens"
    )
    op.drop_index(op.f("ix_verification_tokens_id"), table_name="verification_tokens")
    op.drop_table("verification_tokens")
    # ### end Alembic commands ###
