"""Add user_role column

Revision ID: 4e7d4d5e7661
Revises: a37ad6ed5842
Create Date: 2026-04-06 17:07:47.505824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4e7d4d5e7661"
down_revision: Union[str, Sequence[str], None] = "a37ad6ed5842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_role", sa.String(length=50), server_default="user", nullable=False
        ),
    )
    op.create_index(op.f("ix_users_user_role"), "users", ["user_role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_role"), table_name="users")
    op.drop_column("users", "user_role")
    # ### end Alembic commands ###
