"""Change User.id to UUID

Revision ID: 7f066a8213a8
Revises: e1a664780dc6
Create Date: 2026-03-27 22:35:06.005762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f066a8213a8'
down_revision: Union[str, Sequence[str], None] = 'e1a664780dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Setup extension for UUID generation if needed
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # We truncate because casting int -> uuid with a random function would break existing foreign key relations.
    op.execute('TRUNCATE TABLE users CASCADE')
    
    # Drop foreign key constraint on verification_tokens
    op.drop_constraint('verification_tokens_user_id_fkey', 'verification_tokens', type_='foreignkey')
    
    # Alter the columns
    # Alter the columns. First drop the integer default from the id column to allow cast.
    op.execute('ALTER TABLE users ALTER COLUMN id DROP DEFAULT')
    op.execute('ALTER TABLE users ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4())')
    op.execute('ALTER TABLE verification_tokens ALTER COLUMN user_id SET DATA TYPE UUID USING (uuid_generate_v4())')
    
    # Re-add foreign key constraint
    op.create_foreign_key('verification_tokens_user_id_fkey', 'verification_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_tokens', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
