"""create_rooms_participants_and_invitations

Revision ID: a37ad6ed5842
Revises: a9a4f2fb79b5
Create Date: 2026-04-03 00:58:07.279213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a37ad6ed5842"
down_revision: Union[str, Sequence[str], None] = "a9a4f2fb79b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants", sa.Column("guest_session_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "participants",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
            server_default="Guest",
        ),
    )
    op.alter_column("participants", "user_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        op.f("ix_participants_guest_session_id"),
        "participants",
        ["guest_session_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_participant_room_guest", "participants", ["room_id", "guest_session_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_participant_room_guest", "participants", type_="unique")
    op.drop_index(op.f("ix_participants_guest_session_id"), table_name="participants")
    op.alter_column("participants", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("participants", "display_name")
    op.drop_column("participants", "guest_session_id")
    # ### end Alembic commands ###
