"""create_rooms_participants_and_invitations

Revision ID: a9a4f2fb79b5
Revises: b3eb2b8ac7ed
Create Date: 2026-04-02 18:06:01.694264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a9a4f2fb79b5"
down_revision: Union[str, Sequence[str], None] = "b3eb2b8ac7ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_code", sa.String(length=12), nullable=False),
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_host_id"), "rooms", ["host_id"], unique=False)
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=False)
    op.create_index(op.f("ix_rooms_room_code"), "rooms", ["room_code"], unique=True)
    op.create_index(op.f("ix_rooms_status"), "rooms", ["status"], unique=False)
    op.create_table(
        "meeting_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("inviter_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_invitations_email"),
        "meeting_invitations",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_invitations_id"), "meeting_invitations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_invitations_room_id"),
        "meeting_invitations",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_invitations_token"),
        "meeting_invitations",
        ["token"],
        unique=True,
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "user_id", name="uq_participant_room_user"),
    )
    op.create_index(op.f("ix_participants_id"), "participants", ["id"], unique=False)
    op.create_index(
        op.f("ix_participants_room_id"), "participants", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_participants_user_id"), "participants", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participants_user_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_room_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(
        op.f("ix_meeting_invitations_token"), table_name="meeting_invitations"
    )
    op.drop_index(
        op.f("ix_meeting_invitations_room_id"), table_name="meeting_invitations"
    )
    op.drop_index(op.f("ix_meeting_invitations_id"), table_name="meeting_invitations")
    op.drop_index(
        op.f("ix_meeting_invitations_email"), table_name="meeting_invitations"
    )
    op.drop_table("meeting_invitations")
    op.drop_index(op.f("ix_rooms_status"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_room_code"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_host_id"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
